name: fancy_loader
description: |
  Fancy Loader is a Flutter package that provides visually appealing and customizable loading indicators. It offers various animation types, including gradients, pulsing, and rotating effects, to add style to your loading screens and give your users a pleasant waiting experience.

  With Fancy Loader, you can easily integrate loading animations into your Flutter applications, making them more interactive and engaging. The package allows you to customize the size, duration, and colors of the loading indicators, making it versatile for different use cases.

  Key Features:
  - Gradients, Pulsing, and Rotating animation types.
  - Customizable size, duration, and colors.
  - Easy integration into any Flutter project.
  - Visually appealing loading screens.

version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# Add assets and fonts here if needed

